<template>
  <div>
    <section>
    <div class="wave-wrapper">
      <div class="wave">
          <svg data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 120" preserveAspectRatio="none">
              <path d="M321.39,56.44c58-10.79,114.16-30.13,172-41.86,82.39-16.72,168.19-17.73,250.45-.39C823.78,31,906.67,72,985.66,92.83c70.05,18.48,146.53,26.09,214.34,3V0H0V27.35A600.21,600.21,0,0,0,321.39,56.44Z" class="shape-fill"></path>
          </svg>
      </div>
    </div>
    <div class="tile-section-wrapper">
      <div class="tile-container">
        <div class="tile">
          <div class="front">{{ TileHaeder1 }}</div>
          <div class="back">{{ TileTxt1 }}</div>
        </div>
      </div>
      <div class="tile-container">
        <div class="tile">
          <div class="front">{{ TileHaeder2 }}</div>
          <div class="back">{{ TileTxt2 }}</div>
        </div>
      </div>
      <div class="tile-container">
        <div class="tile">
          <div class="front">{{ TileHaeder3 }}</div>
          <div class="back">{{ TileTxt3 }}</div>
        </div>
      </div>
      <div class="tile-container">
        <div class="tile">
          <div class="front">{{ TileHaeder4 }}</div>
          <div class="back">{{ TileTxt4 }}</div>
        </div>
      </div>
      <div class="tile-container">
        <div class="tile">
          <div class="front">{{ TileHaeder5 }}</div>
          <div class="back">{{ TileTxt5 }}</div>
        </div>
      </div>
      <div class="tile-container">
        <div class="tile">
          <div class="front">{{ TileHaeder6 }}</div>
          <div class="back">{{ TileTxt6 }}</div>
        </div>
      </div>
    </div>
  </section>
  <div clas="spacer layer1"></div>
  <img id="layer1Img" clas="spacer layer1" v-bind:src="layeredWavesSvg">
  </div>
</template>

<script>
export default {
  name: 'Tiles',
  data () {
    return {
      layeredWavesSvg: require('../assets/images/layered-waves-h100.svg'),
      language: '',
      TileHaeder1: 'What is a Context-Sensitive Language?',
      TileTxt1: 'A context-sensitive language is a type of formal language in which the rules for forming valid strings depend on the context of the symbols within the strings. These languages are more powerful than context-free languages and can describe certain computational problems that cannot be represented by simpler language classes.',
      TileHaeder2: 'What is the Word Problem for Context-Sensitive Languages?',
      TileTxt2: 'The Word Problem for Context-Sensitive Languages asks whether a given string can be generated by a particular context-sensitive grammar. It involves determining if the string belongs to the language defined by the grammar, which can be complex due to the nature of context-sensitive rules.',
      TileHaeder3: 'What practical applications exist for the Word Problem in Context-Sensitive Languages?',
      TileTxt3: 'The Word Problem for Context-Sensitive Languages has various use cases in theoretical computer science, including language recognition, compiler design, and artificial intelligence. It helps in understanding the complexities of context-sensitive grammars and their applications in parsing and processing structured information.',
      TileHaeder4: 'How do you use the Website?',
      TileTxt4: '',
      TileHaeder5: 'What is the Purpose of the Website?',
      TileTxt5: '',
      TileHaeder6: 'Further Reading',
      TileTxt6: ''
    }
  },
  mounted () {
    this.initTiles()
  },
  methods: {
    initTiles () {
      this.tiles = document.querySelectorAll('.tile-container')

      this.tiles.forEach(tile => {
        tile.addEventListener('click', () => {
          tile.classList.toggle('clicked')
        })
      })
    }
  }
}
</script>

<style scoped>
.tile-section-wrapper {
  width: 100%;
  height: 500px;
  display: grid;
  grid-template-columns: repeat(3, 33.33%);
  background-color: var(--lmu-gray);
  padding: 30px;
}
.tile-container {
  perspective: 1000px; /* Creates the 3D effect */
  margin: 7px;
}

/* The tile itself */
.tile {
  width: 100%;
  height: 100%;
  position: relative;
  transform-style: preserve-3d; /* Needed for 3D flipping */
  transition: transform 0.6s; /* Controls the flipping speed */
  cursor: pointer;
  box-shadow: 0 10px 20px rgba(0,0,0,0.50), 6px 6px 6px rgba(0,0,0,0.50);
  /* box-shadow: 0 10px 20px rgba(255, 255, 255, 0.3), 6px 6px 6px rgba(255, 255, 255, 0.3); */
}

.tile:hover {
  transform: scale(1.02);
}

/* The front and back of the tile */
.front, .back {
  position: absolute;
  width: 100%;
  height: 100%;
  backface-visibility: hidden; /* Hides the back when it's turned */
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 20px;
  border-radius: 3px;
  padding: 5px;
}

.front {
  background-color: var(--lmu-gray);
  color: white;
  font-weight: bold;
}

.back {
  /* background-color: #297244; */
  background-color: #00883A;
  color: white;
  transform: rotateY(180deg); /* Initially hidden by rotating 180 degrees */
  font-size:medium;
  font-weight: bold;
}

/* Flipping the tile when clicked */
.tile-container.clicked .tile {
  transform: rotateY(180deg); /* Flips the tile */
}
.wave {
    position:static;
    bottom: 0;
    left: 0;
    width: 100%;
    overflow: hidden;
    line-height: 0;
    transform: rotate(180deg);
}

.wave svg {
    position: relative;
    display: block;
    width: calc(140% + 1.3px);
    height: 80px;
}

.wave .shape-fill {
    fill: var(--lmu-gray);
}
.spacer {
  aspect-ratio: 960/100;
  width: 100%;
  background-repeat: no-repeat;
  background-position: center;
  background-size: cover;
}
.layer1 {
  background-image: url(${layeredWavesSvg});
}
#layer1Img {
  width: 100%;
}
</style>
